- hosts: digitalocean
  user: root

  roles:
    - {name: isntall-dante, tags: [isntall, run]}
    - {name: stop-dante, tags: [stop]}
    - {name: configure-dante, tags: [config, run, restart]}
    - {name: start-dante, tags: [start, run, restart]}
