- hosts: digitalocean
  user: root
  vars:
    port:      8888
    username:  default
    password:  cd22b5ba
    hash_solt: 2d81a9df

  roles:
    - {name: isntall-dante, tags: [isntall, run]}
    - {name: stop-dante, tags: [stop]}
    - {name: configure-dante, tags: [config, run, restart]}
    - {name: start-dante, tags: [start, run, restart]}
