#!/usr/bin/env bash


if [ -L ${0} ]
then
    cd "$(dirname "$(readlink "$0")")"
fi

function rand_str() {
    printf "$(openssl rand -hex 8)"
}

function generate_user_config() {
    printf \
    "port: 8888\nusername: default\npassword: $(rand_str)\nsalt: $(rand_str)\n" > \
    config.yml
}

function print_proxy_info() {
    cat config.yml | grep -e 'port' -e 'username' -e 'password'
}

function run_ansible_playbook() {
    ansible-playbook -i hosts playbook.yml --tags "$1"
}

function print_help() {
    printf "usage: proxy [command]\n"
    printf "commands:\n"
    printf "\tsetup   - generate user config file\n"
    printf "\tinfo    - print proxy settings\n"
    printf "\trun     - run ansible playbook to isntall, config and start proxy server\n"
    printf "\tinstall - run ansible playbook to install proxy server\n"
    printf "\tconfig  - run ansible playbook to config proxy server\n"
    printf "\tstart   - run ansible playbook to start proxy server\n"
    printf "\trestart - run ansible playbook to restart proxy server\n"
    printf "\tstop    - run ansible playbook to stop proxy server\n"
}

case "$1" in
"setup")
    generate_user_config
    ;;
"info")
    print_proxy_info
    ;;
"install" | "config" | "stop")
    run_ansible_playbook "$1"
    ;;
"run" | "start" | "restart")
    run_ansible_playbook "$1"
    print_proxy_info
    ;;
*)
    print_help
    ;;
esac
