- name: Include vars of userdata/config.yml into the 'config' variable (2.2).
  include_vars:
    file: userdata/config.yml
    name: config


- name: Generate user password
  shell: python -c 'import crypt; print crypt.crypt("{{ config.password }}", "{{ config.salt }}")'
  register: genpass


- name: Add group for proxy users
  group:
    name: proxy
    state: present


- name: Add user to proxy group
  user:
    name: "{{ config.username }}"
    group: proxy
    password: "{{ genpass.stdout }}"


- name: Replace Dante proxy server config file
  copy:
    src: ../templates/sockd.conf
    dest: /etc/danted.conf
    mode: 0655
